name: ML Pipeline

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Train model
      run: python src/train.py
    - name: Test model
      run: python src/test.py
    - name: Evaluate model
      run: python src/evaluate.py
    - name: Deploy model
      run: python src/deploy.py